





spring:
  h2:
    console:
      enabled: true
      path: /h2 # Access H2 console at /h2-console endpoint

  application:
    name: task-management-system

  datasource:
    url: jdbc:h2:mem:task-management-system  
    driver-class-name: org.h2.Driver
    username: sa
    password: password
    
    # Uncomment below if you want to use H2 in (persistent) mode
    # url: jdbc:h2:~/testdb;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE

  jpa:
    hibernate:
    
          
    
      ddl-auto: update
      hibernate.enable_lazy_load_no_trans: true  
    show-sql: true  

server:
  port: 8083
  shutdown: graceful  
